FROM alpine:3.21 AS builder

RUN apk add --no-cache git

RUN git clone https://git.ffmpeg.org/ffmpeg.git -b release/9.0

WORKDIR /ffmpeg

# ffmpeg build dependencies
RUN apk add --no-cache \
    alpine-sdk \
    pkgconf \
    zlib-dev

RUN ./configure \
    --enable-pic \
    --extra-cflags="-fPIC" \
    --enable-static \
    --disable-iconv \
    --disable-debug \
    --disable-runtime-cpudetect \
    --disable-x86asm \
    --disable-shared \
    --disable-everything \
    --disable-programs \
    --disable-doc \
    --disable-network \
    --disable-autodetect \
    --enable-small \
    --enable-avcodec \
    --enable-avformat \
    --enable-avutil \
    --enable-swresample \
    --enable-decoder=mp3,aac,flac,vorbis,alac \
    --enable-demuxer=mp3,mov,flac,ogg \
    --enable-parser=mpegaudio,aac,flac \
    --enable-protocol=file

RUN make -j$(nproc - 1)

RUN make install DESTDIR=/install