FROM debian:bookworm-slim AS builder

RUN apt-get update && apt-get install -y git

RUN git clone https://git.ffmpeg.org/ffmpeg.git -b release/9.0

WORKDIR /ffmpeg

# ffmpeg build dependencies
RUN apt-get install -y --no-install-recommends \
    build-essential \
    pkg-config \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*


# I can enable ASM with this var, but ffmpeg would not link with my shared libmsp.so.
# AFAIU that's how ffmpeg asm is written and nothing I can do.
# But it shouldn't be an issue because I only use it to decode audio
#ENV ASFLAGS="-DPIC -f elf64"

RUN ./configure \
    --enable-pic \
    --extra-cflags="-fPIC" \
    --enable-static \
    --disable-iconv \
    --disable-debug \
    --disable-runtime-cpudetect \
    --disable-x86asm \
    --disable-shared \
    --disable-everything \
    --disable-programs \
    --disable-doc \
    --disable-network \
    --disable-autodetect \
    --enable-small \
    --enable-avcodec \
    --enable-avformat \
    --enable-avutil \
    --enable-swresample \
    --enable-decoder=mp3,aac,flac,vorbis,opus,alac,pcm_s16le,pcm_s24le,pcm_s32le,pcm_f32le,pcm_f64le,pcm_u8 \
    --enable-demuxer=mp3,mov,flac,ogg,wav \
    --enable-parser=mpegaudio,aac,flac,opus \
    --enable-protocol=file

RUN make -j$(nproc)

RUN make install DESTDIR=/install